
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vinit
 */
public class bloodSugar extends javax.swing.JFrame {

    /**
     * Creates new form bloodSugar
     */
    static String u="";
    public bloodSugar(String userr) {
        initComponents();
        u=userr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHead = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblHeading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bt = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jftPre = new javax.swing.JFormattedTextField();
        btnSubmit = new javax.swing.JButton();
        jftPost = new javax.swing.JFormattedTextField();
        lblT3Error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BloodSugar Test");

        lblHead.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        lblHead.setForeground(new java.awt.Color(0, 153, 0));
        lblHead.setText("Blood Sugar");

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Test Description");

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Obserevd Value");

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Reference Value");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel4.setText("Plasma Glucose");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel5.setText("Plasma glucose Fasting,");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel6.setText("by hexokinase method");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel7.setText("Plasma Glucose post prandial ");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel8.setText("by Heokinase method");

        lblHeading.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(0, 153, 0));
        lblHeading.setText("Test Results");

        bt.setColumns(20);
        bt.setRows(5);
        jScrollPane1.setViewportView(bt);

        btnBack.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 153, 0));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel9.setText("<100mg/dL");

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel10.setText("<140 mg/dL");

        jftPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftPreActionPerformed(evt);
            }
        });
        jftPre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftPreKeyTyped(evt);
            }
        });

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(0, 204, 0));
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jftPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftPostActionPerformed(evt);
            }
        });
        jftPost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftPostKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(btnSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(55, 55, 55)
                                .addComponent(jftPost, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jftPre, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblT3Error, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHead, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(btnBack)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHead, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblT3Error, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jftPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       menuPage t=new menuPage(u);
       t.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
          Connect j=new Connect();
        DBCollection dbc=j.connect("login_details");
      DBCollection dbc1=j.connect("Report");
      DBCollection dbc2=j.connect("bloodSugar");
     String user="";
     String fnm="";
     String lnm="";
     int flag=0;
        BasicDBObject bdb1=new BasicDBObject();
      BasicDBObject bdb2=new BasicDBObject();
        BasicDBObject bdb=new BasicDBObject();
        String a,b;
        String result="";
        a=jftPre.getText();
        b=jftPost.getText();
        bdb.put("Username",u);
        bdb.put("Plasma_Glucose_Fasting",a);
        bdb.put("Plasma_Glucose_Post",b);

        dbc2.insert(bdb);
      
        
        
        
         
      DBCursor cursor = dbc.find();
       
        
       
         BasicDBObject search = new BasicDBObject();
      BasicDBObject newQ = new BasicDBObject();
     BasicDBObject newP=new BasicDBObject();
  if(jftPre.getText().trim().length() == 0 || jftPost.getText().trim().length() == 0)
  {
  JOptionPane.showMessageDialog(null,"Enter all test values");
  }
    
  else
  {
      int c = Integer.parseInt(jftPre.getText());
        int d = Integer.parseInt(jftPost.getText());
     while(cursor.hasNext())     
                {
                    DBObject obj = cursor.next();                    
                   user=(String)obj.get("Email");
                   if(u.equals(user))
                   {
                     fnm=(String)obj.get("Fname");  
                     lnm=(String)obj.get("Lname");  
                    
                   }   
                   }
                    
              DBCursor cursor2 = dbc1.find();
              while(cursor2.hasNext())     
              {
                  DBObject obj2 = cursor2.next();
                     System.out.println(obj2);
                     
                     
                    
                  user=(String)obj2.get("Email");
                   if(u.equals(user)){
                       
                          if(obj2.containsKey("BloodSugar"))
                       {
                           System.out.println("2");
                       BasicDBObject searchQuery = new BasicDBObject("Email",u);
                        BasicDBObject updateFields = new BasicDBObject();
                         updateFields.append("Plasma_Glucose_Fasting",a);
                        updateFields.append("Plasma_Glucose_Post", b);
                        BasicDBObject setQuery = new BasicDBObject();
                        setQuery.append("$set", updateFields);
                        dbc1.update(searchQuery, setQuery);
                        flag=1;
                        break;
                       }
                       else
                       {
                            
                        search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("BloodSugar", "Test"));
                       dbc1.update(search, newQ); 
                        search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("Plasma_Glucose_Fasting",a));
                       dbc1.update(search, newQ);
                        search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("Plasma_Glucose_Fasting",b));
                        dbc1.update(search, newQ);
                        /*search.append("Email",u);   
                        bdb2.put("1","Den");
                       bdb2.put("IgM",igm);
                       bdb2.put("IgG",igg);
                      search.put("Dengue",bdb2);
                      dbc1.insert(search);*/
                       flag=1;
                        break;
                       }
                     
                       
                    }              
              }        
                   if(flag==0)    
                   {
                    //System.out.println("4");
                      newQ.put("Fname",fnm);
                      newQ.put("Lname",lnm); 
                      newQ.put("Email",u);
                      newQ.put("BloodSugar","3"); 
                     newQ.put("Plasma_Glucose_Fasting",a);
                       newQ.put("Plasma_Glucose_Fasting",b);
                        dbc1.insert(newQ); 
                     
                   }
                   

        if(c>=126)
        {
            result=result.concat("Test results are suggestive of diabetes mellitus");
            bt.setText(result);
        }
        else if(c>100 && c<125)
        {
            result=result.concat("Test results are normal for fasting blood sugar test");
            bt.setText(result);
        }

        else
        {
            result=result.concat("Low Sugar");
            bt.setText(result);
        }
        if(d>=200)
        {
            result=result.concat("Test results are suggestive of diabetes mellitus");
            bt.setText(result);

        }
        else if(d>141 && d<199)
        {
            result=result.concat("Test results are normal for fasting blood sugar test");
            bt.setText(result);
        }

        else
        {
            result=result.concat("Low post fasting sugar ");
            bt.setText(result);
        

        }
  }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jftPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftPreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftPreActionPerformed

    private void jftPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftPostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftPostActionPerformed

    private void jftPreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftPreKeyTyped
        // TODO add your handling code here:
         char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     }
    }//GEN-LAST:event_jftPreKeyTyped

    private void jftPostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftPostKeyTyped
        // TODO add your handling code here:
         char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     }
    }//GEN-LAST:event_jftPostKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bloodSugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bloodSugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bloodSugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bloodSugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bloodSugar(u).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bt;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JFormattedTextField jftPost;
    private javax.swing.JFormattedTextField jftPre;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblT3Error;
    // End of variables declaration//GEN-END:variables
}
