
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Creative
 */
public class bloodcount extends javax.swing.JFrame {

    /**
     * Creates new form bloodcount
     */
    static String u="";
    public bloodcount(String userr) {
        initComponents();
        u=userr;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jftT2 = new javax.swing.JFormattedTextField();
        jftT3 = new javax.swing.JFormattedTextField();
        jftT4 = new javax.swing.JFormattedTextField();
        jftT5 = new javax.swing.JFormattedTextField();
        jftT6 = new javax.swing.JFormattedTextField();
        jftT7 = new javax.swing.JFormattedTextField();
        jftT8 = new javax.swing.JFormattedTextField();
        jftT9 = new javax.swing.JFormattedTextField();
        jftT10 = new javax.swing.JFormattedTextField();
        jftT11 = new javax.swing.JFormattedTextField();
        jftT12 = new javax.swing.JFormattedTextField();
        jftT13 = new javax.swing.JFormattedTextField();
        jftT14 = new javax.swing.JFormattedTextField();
        jftT15 = new javax.swing.JFormattedTextField();
        jftT16 = new javax.swing.JFormattedTextField();
        jftT17 = new javax.swing.JFormattedTextField();
        jftT18 = new javax.swing.JFormattedTextField();
        jftT19 = new javax.swing.JFormattedTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jftT1 = new javax.swing.JFormattedTextField();
        jLabel53 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResArea = new javax.swing.JTextArea();
        lblTestRes = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnEmail = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblT3Error = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Haemogram Test");
        setPreferredSize(new java.awt.Dimension(2020, 2200));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(2020, 2200));

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 1500));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Complete Blood Count");

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel2.setText("(EDTA Whole Blood, Automated Cell Counter)");

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("   Result");

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Biological Reference Interval");

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel5.setText("Hemoglobin, EDTA Whole Blood");

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel6.setText("Male :  4.5 - 5.9 X 10^6 /microlitres");

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel7.setText("Female :  12.3 - 15.3 g/dl");

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel8.setText("Total Leucocytes (WBC) Count");

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel9.setText("Male & Female :  4,000 - 10,000 /microlitres");

        jLabel10.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel10.setText("Platelet Count");

        jLabel11.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel11.setText("150,000 - 450,000 /microlitres");

        jLabel12.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel12.setText("Red Blood Cell Count");

        jLabel13.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel13.setText("PCV (Packed Cell Volume)");

        jLabel14.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel14.setText("MCV (Mean Corpuscular Volume)");

        jLabel15.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel15.setText("MCH (Mean Corpuscular Haemoglobin)");

        jLabel16.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel16.setText("MCHC (Mean Corpuscular Haemoglobin Concentration)");

        jLabel17.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel17.setText("RDW (Red Blood Cell Distribution Width)");

        jLabel20.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel20.setText("Absolute Neutrophils");

        jLabel21.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel21.setText("Absolute Eusinophils");

        jLabel22.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel22.setText("Basophils");

        jLabel23.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel23.setText("Eusinophils");

        jLabel24.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel24.setText("Absolute Monocytes");

        jLabel25.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel25.setText("Monocytes");

        jLabel26.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel26.setText("Absolute Basophils");

        jLabel27.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel27.setText("Lymphocytes");

        jLabel28.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel28.setText("Absolute Lymphocytes");

        jLabel29.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 153, 0));
        jLabel29.setText("Differential Count");

        jLabel35.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel35.setText("Male :  14.0 - 17.50 g/dl");

        jLabel36.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel36.setText("Female :  4.1 - 5.1 X 10^6/microlitres");

        jLabel37.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel37.setText("Female :  35.90 - 44.60 %");

        jLabel38.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel38.setText("Male :  41.50 - 50.4 %");

        jLabel39.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel39.setText("80.0 - 96.0 fL");

        jLabel40.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel40.setText("27.5 - 33.2 pgrams");

        jLabel41.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel41.setText("33.4 - 34.5 g/dl");

        jLabel42.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel42.setText("12 - 14 %");

        jLabel44.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel44.setText("2000 - 7000 /microlitres");

        jLabel43.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel43.setText("Neutrophils");

        jftT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT2ActionPerformed(evt);
            }
        });
        jftT2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT2KeyTyped(evt);
            }
        });

        jftT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT3ActionPerformed(evt);
            }
        });
        jftT3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT3KeyTyped(evt);
            }
        });

        jftT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT4ActionPerformed(evt);
            }
        });
        jftT4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jftT4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT4KeyTyped(evt);
            }
        });

        jftT5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT5ActionPerformed(evt);
            }
        });
        jftT5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT5KeyTyped(evt);
            }
        });

        jftT6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT6ActionPerformed(evt);
            }
        });
        jftT6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT6KeyTyped(evt);
            }
        });

        jftT7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT7ActionPerformed(evt);
            }
        });
        jftT7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT7KeyTyped(evt);
            }
        });

        jftT8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT8ActionPerformed(evt);
            }
        });
        jftT8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT8KeyTyped(evt);
            }
        });

        jftT9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT9ActionPerformed(evt);
            }
        });
        jftT9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT9KeyTyped(evt);
            }
        });

        jftT10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT10ActionPerformed(evt);
            }
        });
        jftT10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT10KeyTyped(evt);
            }
        });

        jftT11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT11ActionPerformed(evt);
            }
        });
        jftT11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT11KeyTyped(evt);
            }
        });

        jftT12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT12ActionPerformed(evt);
            }
        });
        jftT12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT12KeyTyped(evt);
            }
        });

        jftT13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT13ActionPerformed(evt);
            }
        });
        jftT13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT13KeyTyped(evt);
            }
        });

        jftT14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT14ActionPerformed(evt);
            }
        });
        jftT14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT14KeyTyped(evt);
            }
        });

        jftT15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT15ActionPerformed(evt);
            }
        });
        jftT15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT15KeyTyped(evt);
            }
        });

        jftT16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT16ActionPerformed(evt);
            }
        });
        jftT16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT16KeyTyped(evt);
            }
        });

        jftT17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT17ActionPerformed(evt);
            }
        });
        jftT17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT17KeyTyped(evt);
            }
        });

        jftT18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT18ActionPerformed(evt);
            }
        });
        jftT18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT18KeyTyped(evt);
            }
        });

        jftT19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT19ActionPerformed(evt);
            }
        });
        jftT19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT19KeyTyped(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel46.setText("%");

        jLabel47.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel47.setText("%");

        jLabel48.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel48.setText("%");

        jLabel49.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel49.setText("%");

        jLabel19.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel19.setText("0 - 500 /microlitres");

        jLabel50.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel50.setText("0 - 100 /microlitres");

        jLabel51.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel51.setText("1000 - 3000 /microlitres");

        jLabel52.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel52.setText("0 - 1000 /microlitres");

        jftT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT1ActionPerformed(evt);
            }
        });
        jftT1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT1KeyTyped(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        jLabel53.setText("%");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 204, 0));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtResArea.setColumns(20);
        txtResArea.setRows(5);
        jScrollPane2.setViewportView(txtResArea);

        lblTestRes.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        lblTestRes.setForeground(new java.awt.Color(0, 204, 0));
        lblTestRes.setText("Test Results");

        btnBack.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 204, 51));
        btnBack.setText("BACK");

        btnEmail.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btnEmail.setForeground(new java.awt.Color(0, 204, 51));
        btnEmail.setText("EMAIL");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 0));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 0));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(lblTestRes, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(215, 215, 215)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jftT9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jftT8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jftT7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jftT6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jftT5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jftT4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jftT3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jftT2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jftT1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jftT10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jftT11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblT3Error, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(128, 128, 128)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel42)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(517, 517, 517)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel20))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(528, 528, 528)
                                        .addComponent(jLabel53))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(492, 492, 492)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel44)
                                            .addComponent(jLabel50)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel51)
                                            .addComponent(jLabel52)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(292, 292, 292)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jftT14, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(214, 214, 214)
                                                .addComponent(jLabel47))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jftT12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(210, 210, 210)
                                                .addComponent(jLabel46))
                                            .addComponent(jftT15, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jftT13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jftT17, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jftT18, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jftT19, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(215, 215, 215)
                                                .addComponent(jLabel49))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jftT16, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(214, 214, 214)
                                                .addComponent(jLabel48))))))
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26)
                            .addComponent(jLabel24)
                            .addComponent(jLabel27)
                            .addComponent(jLabel25)
                            .addComponent(jLabel28)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(101, 101, 101)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnBack)
                        .addGap(647, 647, 647)
                        .addComponent(btnEmail))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(617, 988, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jftT2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftT4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftT5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftT7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftT8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftT9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(jftT10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jftT11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jftT12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftT13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jftT14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jftT15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel50))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jftT16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jftT17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel51)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jftT18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftT19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel52))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTestRes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(375, 375, 375)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(btnEmail)))
                    .addComponent(lblT3Error, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(302, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jftT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT2ActionPerformed

    private void jftT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT3ActionPerformed

    private void jftT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT4ActionPerformed

    private void jftT5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT5ActionPerformed

    private void jftT6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT6ActionPerformed

    private void jftT7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT7ActionPerformed

    private void jftT8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT8ActionPerformed

    private void jftT9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT9ActionPerformed

    private void jftT10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT10ActionPerformed

    private void jftT11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT11ActionPerformed

    private void jftT12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT12ActionPerformed

    private void jftT13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT13ActionPerformed

    private void jftT14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT14ActionPerformed

    private void jftT15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT15ActionPerformed

    private void jftT16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT16ActionPerformed

    private void jftT17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT17ActionPerformed

    private void jftT18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT18ActionPerformed

    private void jftT19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT19ActionPerformed

    private void jftT1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT1KeyTyped
       char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     } 
    }//GEN-LAST:event_jftT1KeyTyped

    private void jftT2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT2KeyTyped
       char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     } 
    }//GEN-LAST:event_jftT2KeyTyped

    private void jftT3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT3KeyTyped
       char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     } 
    }//GEN-LAST:event_jftT3KeyTyped

    private void jftT4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT4KeyReleased

    private void jftT4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT4KeyTyped
       char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     } 
    }//GEN-LAST:event_jftT4KeyTyped

    private void jftT5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT5KeyTyped
        char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     } 
    }//GEN-LAST:event_jftT5KeyTyped

    private void jftT6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT6KeyTyped
       char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     } 
    }//GEN-LAST:event_jftT6KeyTyped

    private void jftT7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT7KeyTyped
        char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     } 
    }//GEN-LAST:event_jftT7KeyTyped

    private void jftT8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT8KeyTyped
       char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     } 
    }//GEN-LAST:event_jftT8KeyTyped

    private void jftT9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT9KeyTyped
       char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     } 
    }//GEN-LAST:event_jftT9KeyTyped

    private void jftT10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT10KeyTyped
         char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     }
    }//GEN-LAST:event_jftT10KeyTyped

    private void jftT11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT11KeyTyped
        // TODO add your handling code here:
         char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     }
    }//GEN-LAST:event_jftT11KeyTyped

    private void jftT12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT12KeyTyped
        char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     } 
    }//GEN-LAST:event_jftT12KeyTyped

    private void jftT13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT13KeyTyped
        char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     } 
    }//GEN-LAST:event_jftT13KeyTyped

    private void jftT14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT14KeyTyped
        char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     } 
    }//GEN-LAST:event_jftT14KeyTyped

    private void jftT15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT15KeyTyped
        // TODO add your handling code here:
        char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     } 
    }//GEN-LAST:event_jftT15KeyTyped

    private void jftT16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT16KeyTyped
        // TODO add your handling code here:
        char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     } 
    }//GEN-LAST:event_jftT16KeyTyped

    private void jftT17KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT17KeyTyped
        // TODO add your handling code here:
        char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     } 
        
    }//GEN-LAST:event_jftT17KeyTyped

    private void jftT18KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT18KeyTyped
        // TODO add your handling code here:
        char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     } 
    }//GEN-LAST:event_jftT18KeyTyped

    private void jftT19KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT19KeyTyped
        // TODO add your handling code here:
           char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     }
    }//GEN-LAST:event_jftT19KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
               
               
               String result="";
               int flag=0;
               
                 String z="";
       String resultt="";
       String user="";
      String fnm="";
      String lnm="";
               Connect j=new Connect();
            DBCollection dbc=j.connect("login_details");
      DBCollection dbc1=j.connect("Report");
      DBCollection dbc2=j.connect("Haemogram_test");
               BasicDBObject bdb=new BasicDBObject();
               bdb.put("Haemoglobin",jftT1.getText());
               bdb.put("WBC",jftT2.getText());
               bdb.put("Platelet",jftT3.getText());
               bdb.put("RBC",jftT4.getText());
               bdb.put("PCV",jftT5.getText());
               bdb.put("MCV",jftT6.getText());
               bdb.put("MCH",jftT7.getText());
               bdb.put("MCHC",jftT8.getText());
               bdb.put("RDW",jftT9.getText());
               bdb.put("Neutrophils",jftT10.getText());
               bdb.put("ABS_Neutrophils",jftT11.getText());
               bdb.put("Eosinophils",jftT12.getText());
               bdb.put("ABS_Eosinophils",jftT13.getText());
               bdb.put("Basophils",jftT14.getText());
               bdb.put("ABS_Basophils",jftT15.getText());
               bdb.put("Lymphocytes",jftT16.getText());
               bdb.put("ABS_Lymphocytes",jftT17.getText());
               bdb.put("Monocytes",jftT18.getText());
               bdb.put("ABS_Monocytes",jftT19.getText());
               dbc.insert(bdb);
              
               float a = Float.parseFloat(jftT1.getText());  
              float b = Float.parseFloat(jftT2.getText());
              float c = Float.parseFloat(jftT3.getText());
               float d = Float.parseFloat(jftT4.getText());
               float e = Float.parseFloat(jftT5.getText());
               float f = Float.parseFloat(jftT6.getText());
               float g = Float.parseFloat(jftT7.getText());
               float h = Float.parseFloat(jftT8.getText());
               float i = Float.parseFloat(jftT9.getText());
               float k = Float.parseFloat(jftT10.getText());
               float l = Float.parseFloat(jftT11.getText());
               float m = Float.parseFloat(jftT12.getText());
               float n = Float.parseFloat(jftT13.getText());
               float o = Float.parseFloat(jftT14.getText());
               float p = Float.parseFloat(jftT15.getText());
               float q = Float.parseFloat(jftT16.getText());
               float r = Float.parseFloat(jftT17.getText());
               float s = Float.parseFloat(jftT18.getText());
               float t = Float.parseFloat(jftT19.getText());
              
               
     
        BasicDBObject bdb1=new BasicDBObject();
      BasicDBObject bdb2=new BasicDBObject();
      DBCursor cursor = dbc.find();
       
        
      
         BasicDBObject search = new BasicDBObject();
      BasicDBObject newQ = new BasicDBObject();
     BasicDBObject newP=new BasicDBObject();
   if(jftT1.getText().trim().length() == 0 || jftT2.getText().trim().length() == 0 || jftT3.getText().trim().length() == 0 || jftT4.getText().trim().length() == 0
           || jftT5.getText().trim().length() == 0 || jftT6.getText().trim().length() == 0 || jftT7.getText().trim().length() == 0 || jftT8.getText().trim().length() == 0
           || jftT9 .getText().trim().length() == 0 || jftT10.getText().trim().length() == 0 || jftT11.getText().trim().length() == 0 || jftT12.getText().trim().length() == 0
           || jftT13.getText().trim().length() == 0 || jftT14.getText().trim().length() == 0 || jftT15.getText().trim().length() == 0 || jftT16.getText().trim().length() == 0
           || jftT17.getText().trim().length() == 0 || jftT18.getText().trim().length() == 0 || jftT19.getText().trim().length() == 0)
  {
    JOptionPane.showMessageDialog(null,"Enter all test values");
  }
    
                       
     while(cursor.hasNext())     
                {
                    DBObject obj = cursor.next();                    
                   user=(String)obj.get("Email");
                   if(u.equals(user))
                   {
                     fnm=(String)obj.get("Fname");  
                     lnm=(String)obj.get("Lname");  
                    
                   }   
                   }
                    
              DBCursor cursor2 = dbc1.find();
              while(cursor2.hasNext())     
              {
                  DBObject obj2 = cursor2.next();
                     System.out.println(obj2);
                     
                     
                     
                  user=(String)obj2.get("Email");
                   if(u.equals(user)){
                       //d=(String)obj2.get("Dengue");
                       //System.out.println("1");
                          if(obj2.containsKey("Haemogram"))
                       {
                           
                       BasicDBObject searchQuery = new BasicDBObject("Email",u);
                        BasicDBObject updateFields = new BasicDBObject();
                        bdb.put("Haemoglobin",jftT1.getText());
               updateFields.append("WBC",jftT2.getText());
               updateFields.append("Platelet",jftT3.getText());
               updateFields.append("RBC",jftT4.getText());
               updateFields.append("PCV",jftT5.getText());
               updateFields.append("MCV",jftT6.getText());
               updateFields.append("MCH",jftT7.getText());
               updateFields.append("MCHC",jftT8.getText());
               updateFields.append("RDW",jftT9.getText());
               updateFields.append("Neutrophils",jftT10.getText());
               updateFields.append("ABS_Neutrophils",jftT11.getText());
               updateFields.append("Eosinophils",jftT12.getText());
               updateFields.append("ABS_Eosinophils",jftT13.getText());
               updateFields.append("Basophils",jftT14.getText());
               updateFields.append("ABS_Basophils",jftT15.getText());
               updateFields.append("Lymphocytes",jftT16.getText());
               updateFields.append("ABS_Lymphocytes",jftT17.getText());
               updateFields.append("Monocytes",jftT18.getText());
               updateFields.append("ABS_Monocytes",jftT19.getText());
                         
                        BasicDBObject setQuery = new BasicDBObject();
                        setQuery.append("$set", updateFields);
                        dbc1.update(searchQuery, setQuery);
                        flag=1;
                        break;
                       }
                       else
                       {
                         
                        search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("Haemogram", "1"));
                       dbc1.update(search, newQ); 
                        search.append("Email",u );
                        newQ.put("$set", new BasicDBObject().append("Haemoglobin",jftT1.getText()));
                       dbc1.update(search, newQ); 
                        search.append("Email",u );
                        newQ.put("$set", new BasicDBObject().append("WBC",jftT2.getText()));
                       dbc1.update(search, newQ); 
                        search.append("Email",u );
                        newQ.put("$set", new BasicDBObject().append("Platelet",jftT3.getText()));
                       dbc1.update(search, newQ); 
                        search.append("Email",u );
                        newQ.put("$set", new BasicDBObject().append("RBC",jftT4.getText()));
                       dbc1.update(search, newQ); 
                        search.append("Email",u );
                        newQ.put("$set", new BasicDBObject().append("PCV",jftT5.getText()));
                       dbc1.update(search, newQ); 
                        search.append("Email",u );
                        newQ.put("$set", new BasicDBObject().append("MCV",jftT6.getText()));
                       dbc1.update(search, newQ); 
                        search.append("Email",u );
                        newQ.put("$set", new BasicDBObject().append("MCH",jftT7.getText()));
                       dbc1.update(search, newQ); 
                        search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("MCHC",jftT8.getText()));
                       dbc1.update(search, newQ);
                        search.append("Email",u );
                         newQ.put("$set", new BasicDBObject().append("MCHC",jftT8.getText()));
                       dbc1.update(search, newQ);
                        search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("RDW",jftT9.getText()));
                        dbc1.update(search, newQ);
                        search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("Neutrophils",jftT10.getText()));
                        dbc1.update(search, newQ);
                        search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("ABS_Neutrophils",jftT11.getText()));
                        dbc1.update(search, newQ);
                        search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("Eosinophils",jftT12.getText()));
                        dbc1.update(search, newQ);
                        search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("ABS_Eosinophils",jftT13.getText()));
                        dbc1.update(search, newQ);
                        search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("Basophils",jftT14.getText()));
                        dbc1.update(search, newQ);
                        search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("ABS_Basophils",jftT15.getText()));
                        dbc1.update(search, newQ);
                        search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("Lymphocytes",jftT16.getText()));
                        dbc1.update(search, newQ);
                        search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("ABS_Lymphocytes",jftT17.getText()));
                        dbc1.update(search, newQ);
                         search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("Monocytes",jftT18.getText()));
                        dbc1.update(search, newQ);
                         search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("ABS_Monocytes",jftT19.getText()));
                        dbc1.update(search, newQ);
                        /*search.append("Email",u);   
                        bdb2.put("1","Den");
                       bdb2.put("IgM",igm);
                       bdb2.put("IgG",igg);
                      search.put("Dengue",bdb2);
                      dbc1.insert(search);*/
                       flag=1;
                        break;
                       }
                     
                       
                    }              
              }        
                   if(flag==0)    
                   {
                    //System.out.println("4");
                      newQ.put("Fname",fnm);
                      newQ.put("Lname",lnm); 
                      newQ.put("Email",u);
                      newQ.put("Haemogram","1"); 
                     
                       newQ.put("Haemoglobin",jftT1.getText());
               newQ.put("WBC",jftT2.getText());
               newQ.put("Platelet",jftT3.getText());
               newQ.put("RBC",jftT4.getText());
               newQ.put("PCV",jftT5.getText());
               newQ.put("MCV",jftT6.getText());
               newQ.put("MCH",jftT7.getText());
               newQ.put("MCHC",jftT8.getText());
               newQ.put("RDW",jftT9.getText());
               newQ.put("Neutrophils",jftT10.getText());
               newQ.put("ABS_Neutrophils",jftT11.getText());
               newQ.put("Eosinophils",jftT12.getText());
               newQ.put("ABS_Eosinophils",jftT13.getText());
               newQ.put("Basophils",jftT14.getText());
               newQ.put("ABS_Basophils",jftT15.getText());
               newQ.put("Lymphocytes",jftT16.getText());
               newQ.put("ABS_Lymphocytes",jftT17.getText());
               newQ.put("Monocytes",jftT18.getText());
               newQ.put("ABS_Monocytes",jftT19.getText());
                        dbc1.insert(newQ); 
                     
                   }
                     
                
                
                
                
                    if(a<=13)
                  {
                     result=result.concat("\nHaemoglobin is less");
                     txtResArea.setText(result);
                  }
                   else if(a>=16)
                   {
                     result=result.concat("\nHaemoglobin is more");
                     txtResArea.setText(result);
                   }
                   else
                    {
                     result=result.concat("\nHaemoglobin is normal");
                     txtResArea.setText(result);
                    }
                  if(b<=4000)
                   {
                     result=result.concat("\nWBC count is running  less so possibility of LYMPHONA");
                     txtResArea.setText(result);
                   }
                 else if(b>=10000)
{
result=result.concat("\nTest suggests possibility of LUKOCYTOSIS");
txtResArea.setText(result);
}
else
{
result=result.concat("\nWBC is normal");
txtResArea.setText(result);
}
if(d<4)
{
result=result.concat("\nRBC is less,High possibility of ANAEMIA");
txtResArea.setText(result);
}
else if(d>6)
{
result=result.concat("\nRBC count is high,chances of POLYCYTXTRESAREAEMIA");
txtResArea.setText(result);
}
else
{
result=result.concat("\nRBC count is NORMAL....:)");
txtResArea.setText(result);
}
if(e<41)
{
result=result.concat("\nPCV is low,High possibility of ANAEMIA");
txtResArea.setText(result);
}
else if(e>50)
{
result=result.concat("\nPCV  is high,chances of POLYCYTXTRESAREAEMIA");
txtResArea.setText(result);
}
else
{
result=result.concat("\nPCV is NORMAL....:)");
txtResArea.setText(result);
}
if(f<80)
{
result=result.concat("\nMCV is low,High possibility of TXTRESAREAALASSEMIA");
txtResArea.setText(result);
}
else if(f>96)
{
result=result.concat("\nMCV is high,chances of MYELODYSPLASIA");
txtResArea.setText(result);
}
else
{
result=result.concat("\nMCV is NORMAL....:)");
txtResArea.setText(result);
}
if(g<27)
{
result=result.concat("\nMCH is low,High possibility of TXTRESAREAALASSEMIA");
txtResArea.setText(result);
}
else if(g>33)
{
result=result.concat("\nMCH is high,chances of FOLATE DEFICIENCY");
txtResArea.setText(result);
}
else
{
result=result.concat("\nMCH is NORMAL....:)");
txtResArea.setText(result);
}
if(h<33)
{
result=result.concat("\nMCHC is less,High possibility of ANAEMIA(IRON DEFICIENCY)");
txtResArea.setText(result);
}
else if(h>33)
{
result=result.concat("\nMCHC is high,chances of HEMOLYTIC ANAEMIA");
txtResArea.setText(result);
}
else
{
result=result.concat("\nMCHC is NORMAL....:)");
txtResArea.setText(result);
}
if(k<2000)
{
result=result.concat("\nNeutrophil is less,High possibility of MYCLODYSPLASIA");
txtResArea.setText(result);
}
else if(k>7000)
{
result=result.concat("\nNeutrophils is high,symptoms of CUSHING SYNDROME");
txtResArea.setText(result);
}
else
{
result=result.concat(" \nNeutrophils is NORMAL....:)");
txtResArea.setText(result);
}
if(m<0)
{
result=result.concat("\nEosinophils is less,No immediate Signigicance");
txtResArea.setText(result);
}
else if(m>500)
{
result=result.concat("\nEosinophils is high,symptoms of PARASITIC INFECTION");
txtResArea.setText(result);
}
else
{
result=result.concat("\nEosinophils is NORMAL....:)");
txtResArea.setText(result);
}
if(q<1000)
{
result=result.concat("\nLymphocytes are less,High possibility of AUTOIMMUNE DISORDER");
txtResArea.setText(result);
}
else if(q>3000)
{
result=result.concat("\nLymphocytes are high,chances of TOXOPLASMOSIS");
txtResArea.setText(result);
}
else
{
result=result.concat("\nLYMPHOCYTES are NORMAL....:)");
txtResArea.setText(result);
}
if(s<0)
{
result=result.concat("\nMonocytes are less, possibility of APLASTIC ANAEMIA");
txtResArea.setText(result);
}
else if(s>1000)
{
result=result.concat("\nMONOCYTES are high,symptoms of COLLAGEN VASCULAR DISEASE");
txtResArea.setText(result);
}
else
{
result=result.concat("\nRBC count is NORMAL....:)");
txtResArea.setText(result);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jftT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        menuPage mp=new menuPage(u);
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         menuPage mp=new menuPage(u);
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bloodcount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bloodcount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bloodcount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bloodcount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bloodcount(u).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEmail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JFormattedTextField jftT1;
    private javax.swing.JFormattedTextField jftT10;
    private javax.swing.JFormattedTextField jftT11;
    private javax.swing.JFormattedTextField jftT12;
    private javax.swing.JFormattedTextField jftT13;
    private javax.swing.JFormattedTextField jftT14;
    private javax.swing.JFormattedTextField jftT15;
    private javax.swing.JFormattedTextField jftT16;
    private javax.swing.JFormattedTextField jftT17;
    private javax.swing.JFormattedTextField jftT18;
    private javax.swing.JFormattedTextField jftT19;
    private javax.swing.JFormattedTextField jftT2;
    private javax.swing.JFormattedTextField jftT3;
    private javax.swing.JFormattedTextField jftT4;
    private javax.swing.JFormattedTextField jftT5;
    private javax.swing.JFormattedTextField jftT6;
    private javax.swing.JFormattedTextField jftT7;
    private javax.swing.JFormattedTextField jftT8;
    private javax.swing.JFormattedTextField jftT9;
    private javax.swing.JLabel lblT3Error;
    private javax.swing.JLabel lblTestRes;
    private javax.swing.JTextArea txtResArea;
    // End of variables declaration//GEN-END:variables
}
