
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vinit
 */
public class ChangeP extends javax.swing.JFrame {

    /**
     * Creates new form ChangeP
     */
    public ChangeP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        pwdNew = new javax.swing.JPasswordField();
        pwdCon = new javax.swing.JPasswordField();
        pwdOld = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Password\n");
        setPreferredSize(new java.awt.Dimension(631, 419));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("OLD PASSWORD:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 160, 170, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("CONFIRM PASSWORD:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 280, 220, 22);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("USERNAME:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 100, 130, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("NEW PASSWORD:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 220, 180, 22);
        getContentPane().add(txtUser);
        txtUser.setBounds(290, 80, 220, 40);
        getContentPane().add(pwdNew);
        pwdNew.setBounds(290, 210, 220, 40);
        getContentPane().add(pwdCon);
        pwdCon.setBounds(290, 280, 220, 40);

        pwdOld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdOldActionPerformed(evt);
            }
        });
        getContentPane().add(pwdOld);
        pwdOld.setBounds(290, 140, 220, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 204));
        jButton1.setText("SUBMIT");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 360, 120, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\xyz\\Desktop\\maxresdefault.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pwdOldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdOldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdOldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          String pwd = null,user = null; 
        String p = null,u = null;
        String pwd1="";
         String pwd2="";
        int flag = 0;
         final     JPanel p1 = new JPanel(); 

        pwdOld.selectAll();
        pwd = pwdOld.getSelectedText();
        user = txtUser.getText();
        pwdNew.selectAll();
        pwd1 = pwdNew.getSelectedText();
        pwdCon.selectAll();
        pwd2 = pwdCon.getSelectedText();
        if (user.matches("^[A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})")){
      
        //dbc.insert(bdb);  
        /*Start ap=new Start();
        ap.setVisible(true);
        this.dispose();*/
        }
        else {
        JOptionPane.showMessageDialog(null,"Invalid E-mail ID");
        } 
        Connect c = new Connect();
        DBCollection dbc = c.connect("login_details");
        DBCursor cursor = dbc.find();  
            BasicDBObject search=new BasicDBObject();
             BasicDBObject bdb2=new BasicDBObject();
        while(cursor.hasNext())     
                {
                    DBObject obj = cursor.next();                    
                   u=(String)obj.get("Email");
                   p=(String)obj.get("Password");          

                    if((p.equals(pwd)) && (u.equals(user)))
                    {   
                                             
                        flag=1;
                        
                      BasicDBObject bdb=new BasicDBObject().append("$set",new BasicDBObject().append("Password",pwd1));
                     dbc.update(new BasicDBObject().append("Email",user),bdb2);
                     if(pwd1.equals(pwd2))
                     {
                      JOptionPane.showMessageDialog(p1,"Password Changed","success", JOptionPane.INFORMATION_MESSAGE);
                      loginP lp=new loginP();
                      lp.setVisible(true);
                      this.dispose();
                     }

                    }
                }//end of while
                    if(flag==0)
                    {
                        JOptionPane.showMessageDialog(p1,"Incorrect Password","login eror",JOptionPane.ERROR_MESSAGE );
                    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField pwdCon;
    private javax.swing.JPasswordField pwdNew;
    private javax.swing.JPasswordField pwdOld;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
