
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static org.bson.BSON.NULL;
import sun.security.util.Password;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vinit
 */
public class loginP extends javax.swing.JFrame {

    /**
     * Creates new form loginP
     */
    //btnLog1.setOpaque(false);
//btnLog1.setContentAreaFilled(false);
//button.setBorderPainted(false);
    public loginP() {
        //btnLog1.setOpaque(false);
//btnLog1.setContentAreaFilled(false);
//btnLog1.setBorderPainted(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsernm = new javax.swing.JTextField();
        pwdPass = new javax.swing.JPasswordField();
        btnLog = new javax.swing.JButton();
        btnLog1 = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Log In");
        setPreferredSize(new java.awt.Dimension(1095, 507));
        getContentPane().setLayout(null);

        txtUsernm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUsernm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernmActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsernm);
        txtUsernm.setBounds(510, 200, 200, 30);

        pwdPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pwdPass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pwdPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdPassActionPerformed(evt);
            }
        });
        getContentPane().add(pwdPass);
        pwdPass.setBounds(510, 290, 200, 30);

        btnLog.setBackground(new java.awt.Color(117, 200, 159));
        btnLog.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btnLog.setIcon(new javax.swing.ImageIcon("C:\\Users\\xyz\\Desktop\\login.png")); // NOI18N
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });
        btnLog.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btnLogPropertyChange(evt);
            }
        });
        getContentPane().add(btnLog);
        btnLog.setBounds(440, 390, 130, 40);

        btnLog1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btnLog1.setIcon(new javax.swing.ImageIcon("C:\\Users\\xyz\\Desktop\\previous (1).png")); // NOI18N
        btnLog1.setContentAreaFilled(false);
        btnLog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLog1ActionPerformed(evt);
            }
        });
        btnLog1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btnLog1PropertyChange(evt);
            }
        });
        getContentPane().add(btnLog1);
        btnLog1.setBounds(10, 0, 81, 70);

        lblUser.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(0, 153, 204));
        lblUser.setText("Username:");
        getContentPane().add(lblUser);
        lblUser.setBounds(330, 190, 160, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\xyz\\Desktop\\images (1).jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(810, 0, 250, 140);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Password:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 280, 140, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("(Username should be a valid Email id)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 230, 240, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\xyz\\Desktop\\3500031.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1050, 500);

        setBounds(0, 0, 1076, 546);
    }// </editor-fold>//GEN-END:initComponents

    private void pwdPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdPassActionPerformed
        // TODO add your handling code here:
       String pwd = null,user = null; 
        String p = null,u = null;
        int flag = 0;
         final     JPanel p1 = new JPanel(); 

        pwdPass.selectAll();
        pwd = pwdPass.getSelectedText();
        user = txtUsernm.getText();
       
        Connect c = new Connect();
        DBCollection dbc = c.connect("login_details");
        DBCursor cursor = dbc.find();  
            
        while(cursor.hasNext())     
                {
                    DBObject obj = cursor.next();                    
                   u=(String)obj.get("Email");
                   p=(String)obj.get("Password");          

                    if((p.equals(pwd)) && (u.equals(user)))
                    {   
                        this.setVisible(false);                        
                        flag=1;                        
                        NewJFrame t =new NewJFrame(u);
                        System.out.println("TEST");
                        t.setVisible(true);                   
                        break;
                    }
                }//end of while
                    if(flag==0)
                    {
                        JOptionPane.showMessageDialog(p1,"Incorrect Username or Password","login eror",JOptionPane.ERROR_MESSAGE );
                    }
    }//GEN-LAST:event_pwdPassActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        String pwd = null,user = null; 
        String p = null,u = null;
        int flag = 0;
         final     JPanel p1 = new JPanel(); 
        Connect c = new Connect();
        DBCollection dbc = c.connect("login_details");
        
        pwdPass.selectAll();
        pwd = pwdPass.getSelectedText();
        user = txtUsernm.getText();
        if (user.matches("^[A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})")){
       
        //dbc.insert(bdb);  
        /*Start ap=new Start();
        ap.setVisible(true);
        this.dispose();*/
        }
        else {
        JOptionPane.showMessageDialog(null,"Invalid E-mail ID");
        }
        
            /*BasicDBObject search=new BasicDBObject();
             BasicDBObject bdb=new BasicDBObject();*/
             DBCursor cursor = dbc.find(); 
        while(cursor.hasNext())     
                {
                    System.out.println("hello");
                    DBObject obj = cursor.next();                    
                   u = (String)obj.get("Email");
                   p = (String)obj.get("Password");          

                    if((p.equals(pwd))&&(u.equals(user)))
                    {   
                       // this.setVisible(false);                        
                        flag=1;
                        
                       NewJFrame t =new NewJFrame(u);
                       this.dispose();
                        
                        t.setVisible(true);                   
                        break;
                    }
                }//end of while
                    if(flag==0)
                    {
                        JOptionPane.showMessageDialog(p1,"Incorrect Username or Password","login eror",JOptionPane.ERROR_MESSAGE );
                    }
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnLog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLog1ActionPerformed
         Start ap=new Start();
        ap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLog1ActionPerformed

    private void btnLogPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btnLogPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnLogPropertyChange

    private void btnLog1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btnLog1PropertyChange
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnLog1PropertyChange

    private void txtUsernmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernmActionPerformed
        // TODO add your handling code here:
       

    }//GEN-LAST:event_txtUsernmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnLog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField pwdPass;
    private javax.swing.JTextField txtUsernm;
    // End of variables declaration//GEN-END:variables
}
