/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Soniya
 */
public class menuPage extends javax.swing.JFrame {

    /**
     * Creates new form menuPage
     */
    static String u="";
    public menuPage(String userr) {
        initComponents();
        u=userr;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHead = new javax.swing.JLabel();
        lblHaemogram = new javax.swing.JLabel();
        lblDengue = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLipidProfile = new javax.swing.JLabel();
        lblSugar = new javax.swing.JLabel();
        btnT1 = new javax.swing.JButton();
        lblThyroid = new javax.swing.JButton();
        btnT3 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnDengue = new javax.swing.JButton();
        btnT5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Take A Test");
        setPreferredSize(new java.awt.Dimension(1176, 792));
        getContentPane().setLayout(null);

        lblHead.setBackground(new java.awt.Color(255, 255, 255));
        lblHead.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        lblHead.setText("                                                                SELECT A TEST");
        getContentPane().add(lblHead);
        lblHead.setBounds(0, 20, 1020, 40);

        lblHaemogram.setBackground(new java.awt.Color(255, 255, 255));
        lblHaemogram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgonline-com-ua-resize-0umtcCAIsk6l.jpg"))); // NOI18N
        lblHaemogram.setText("jLabel2");
        lblHaemogram.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblHaemogram);
        lblHaemogram.setBounds(70, 70, 179, 180);

        lblDengue.setBackground(new java.awt.Color(255, 255, 255));
        lblDengue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgonline-com-ua-resize-mj7GRe2DydMT.jpg"))); // NOI18N
        lblDengue.setText("jLabel2");
        lblDengue.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblDengue);
        lblDengue.setBounds(260, 370, 179, 180);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgonline-com-ua-resize-iAd0DmknMKVa.jpg"))); // NOI18N
        jLabel4.setText("jLabel2");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 70, 179, 180);

        lblLipidProfile.setBackground(new java.awt.Color(255, 255, 255));
        lblLipidProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgonline-com-ua-resize-nB6VOK3H2hwF.jpg"))); // NOI18N
        lblLipidProfile.setText("jLabel2");
        lblLipidProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblLipidProfile);
        lblLipidProfile.setBounds(650, 370, 179, 180);

        lblSugar.setBackground(new java.awt.Color(255, 255, 255));
        lblSugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgonline-com-ua-resize-lQ6UGLRSF7zO.jpg"))); // NOI18N
        lblSugar.setText("jLabel2");
        lblSugar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblSugar);
        lblSugar.setBounds(830, 70, 179, 180);

        btnT1.setBackground(new java.awt.Color(255, 255, 255));
        btnT1.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        btnT1.setForeground(new java.awt.Color(255, 0, 51));
        btnT1.setText("Haemogram");
        btnT1.setBorder(new javax.swing.border.MatteBorder(null));
        btnT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnT1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnT1);
        btnT1.setBounds(100, 270, 130, 48);

        lblThyroid.setBackground(new java.awt.Color(255, 255, 255));
        lblThyroid.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lblThyroid.setForeground(new java.awt.Color(255, 0, 0));
        lblThyroid.setText("Thyroid");
        lblThyroid.setBorder(new javax.swing.border.MatteBorder(null));
        lblThyroid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblThyroidActionPerformed(evt);
            }
        });
        getContentPane().add(lblThyroid);
        lblThyroid.setBounds(470, 280, 115, 48);

        btnT3.setBackground(new java.awt.Color(255, 255, 255));
        btnT3.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        btnT3.setForeground(new java.awt.Color(255, 0, 51));
        btnT3.setText("Sugar");
        btnT3.setBorder(new javax.swing.border.MatteBorder(null));
        btnT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnT3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnT3);
        btnT3.setBounds(860, 280, 115, 48);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 0, 0));
        btnBack.setText("BACK");
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(1020, 10, 150, 40);

        btnDengue.setBackground(new java.awt.Color(255, 255, 255));
        btnDengue.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        btnDengue.setForeground(new java.awt.Color(255, 0, 0));
        btnDengue.setText("Dengue");
        btnDengue.setBorder(new javax.swing.border.MatteBorder(null));
        btnDengue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDengueActionPerformed(evt);
            }
        });
        getContentPane().add(btnDengue);
        btnDengue.setBounds(290, 580, 115, 48);

        btnT5.setBackground(new java.awt.Color(255, 255, 255));
        btnT5.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        btnT5.setForeground(new java.awt.Color(255, 51, 51));
        btnT5.setText("Lipid Profile");
        btnT5.setBorder(new javax.swing.border.MatteBorder(null));
        btnT5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnT5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnT5);
        btnT5.setBounds(670, 580, 130, 48);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/4j47i9.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1170, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnT1ActionPerformed
        // TODO add your handling code here:
        bloodcount bc=new bloodcount(u);
        bc.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnT1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
   NewJFrame lp=new NewJFrame(u);
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void lblThyroidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblThyroidActionPerformed
         thyroidTest tt=new thyroidTest(u);
        tt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblThyroidActionPerformed

    private void btnT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnT3ActionPerformed
     bloodSugar bs=new bloodSugar(u);
     bs.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnT3ActionPerformed

    private void btnDengueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDengueActionPerformed
       dengueTest dt=new dengueTest(u);
       dt.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnDengueActionPerformed

    private void btnT5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnT5ActionPerformed
        // TODO add your handling code here:
        Lipidprofiletest lpt=new Lipidprofiletest(u);
        lpt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnT5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPage(u).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDengue;
    private javax.swing.JButton btnT1;
    private javax.swing.JButton btnT3;
    private javax.swing.JButton btnT5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDengue;
    private javax.swing.JLabel lblHaemogram;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblLipidProfile;
    private javax.swing.JLabel lblSugar;
    private javax.swing.JButton lblThyroid;
    // End of variables declaration//GEN-END:variables

    void setVisisble(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
