
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
//import static thyroidTest.u;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Soniya
 */
public class thyroidTest extends javax.swing.JFrame {

    private static Object jA;

    private static void add(thyroid jA) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form thyroidTest
     */
    static String u="";
    public thyroidTest(String userr) {
        
        initComponents();
        u=userr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblT1 = new javax.swing.JLabel();
        lblT2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblT6 = new javax.swing.JLabel();
        lblT7 = new javax.swing.JLabel();
        lblT9 = new javax.swing.JLabel();
        lblT3 = new javax.swing.JLabel();
        lblT5 = new javax.swing.JLabel();
        lblT15 = new javax.swing.JLabel();
        lblT18 = new javax.swing.JLabel();
        lblT19 = new javax.swing.JLabel();
        lblT4 = new javax.swing.JLabel();
        lblT8 = new javax.swing.JLabel();
        lblT11 = new javax.swing.JLabel();
        lblT14 = new javax.swing.JLabel();
        btnT1 = new javax.swing.JButton();
        txtT3 = new javax.swing.JFormattedTextField();
        jftT1 = new javax.swing.JFormattedTextField();
        jftT2 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        thyroid = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        lblresult = new javax.swing.JLabel();
        lblT3Error = new javax.swing.JLabel();
        btnT2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thyroid Test");

        lblT1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblT1.setForeground(new java.awt.Color(0, 102, 0));
        lblT1.setText("THYROID TEST");

        lblT2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblT2.setForeground(new java.awt.Color(255, 0, 0));
        lblT2.setText("TEST NAME");

        lblT6.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblT6.setText("Total Triiodothyronine(T3)");

        lblT7.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblT7.setText("Total Thyroxine(T4)");

        lblT9.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblT9.setText("Thyroid Stimulating Hormone(TSH)");

        lblT3.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblT3.setForeground(new java.awt.Color(255, 0, 0));
        lblT3.setText("VALUE");

        lblT5.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblT5.setForeground(new java.awt.Color(255, 0, 0));
        lblT5.setText("REFERENCE RANGE");

        lblT15.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblT15.setText("60-200");

        lblT18.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblT18.setText("4.5-12.0");

        lblT19.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblT19.setText("0.30-5.5");

        lblT4.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblT4.setForeground(new java.awt.Color(255, 0, 0));
        lblT4.setText("UNITS");

        lblT8.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblT8.setText("ng/dl");

        lblT11.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblT11.setText("microg/dl");

        lblT14.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblT14.setText("microIU/ml");

        btnT1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btnT1.setForeground(new java.awt.Color(0, 153, 51));
        btnT1.setText("Submit");
        btnT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnT1ActionPerformed(evt);
            }
        });

        txtT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtT3ActionPerformed(evt);
            }
        });
        txtT3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtT3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtT3KeyTyped(evt);
            }
        });

        jftT1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jftT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT1ActionPerformed(evt);
            }
        });
        jftT1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT1KeyTyped(evt);
            }
        });

        jftT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftT2ActionPerformed(evt);
            }
        });
        jftT2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftT2KeyTyped(evt);
            }
        });

        thyroid.setColumns(20);
        thyroid.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        thyroid.setForeground(new java.awt.Color(255, 0, 0));
        thyroid.setRows(5);
        thyroid.setEnabled(false);
        jScrollPane1.setViewportView(thyroid);

        lblresult.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblresult.setForeground(new java.awt.Color(0, 204, 51));
        lblresult.setText("Test Results");

        lblT3Error.setEnabled(false);

        btnT2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btnT2.setForeground(new java.awt.Color(0, 153, 51));
        btnT2.setText("Back");
        btnT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnT2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblT1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblT6, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(162, 162, 162)
                                                .addComponent(txtT3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(162, 162, 162)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblT8)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addComponent(lblT14)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(lblT19))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addComponent(lblT11)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(lblT18))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addGap(257, 257, 257)
                                                            .addComponent(lblT15)))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(109, 109, 109)
                                                .addComponent(lblT3Error, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(134, 134, 134)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblT2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(336, 336, 336)
                        .addComponent(lblT3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(lblT4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblT5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblT9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblT7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jftT1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jftT2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(554, 554, 554)
                        .addComponent(lblresult, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 665, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnT1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(742, 742, 742)
                        .addComponent(btnT2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblT1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblT3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblT5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblT4))
                    .addComponent(lblT2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblT3Error, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblT6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblT15)
                    .addComponent(lblT8)
                    .addComponent(txtT3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jftT1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblT11)
                            .addComponent(lblT18)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblT7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblT9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblT19)
                            .addComponent(lblT14)))
                    .addComponent(jftT2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnT1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnT2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblresult, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnT1ActionPerformed
        // TODO add your handling code here:
      Connect j=new Connect();
      DBCollection dbc2=j.connect("thyroid_test");
      DBCollection dbc=j.connect("login_details");
      DBCollection dbc1=j.connect("Report");
     
      
      BasicDBObject bdb=new BasicDBObject();
      BasicDBObject bdb1=new BasicDBObject();
      BasicDBObject bdb2=new BasicDBObject();
       String t3,t4,tsh;
       String fnm="";
       
       String lnm="";
       int flag = 0;
       String d="";
       String user = "";
       t3 = txtT3.getText();
       t4 = jftT1.getText();
       tsh = jftT2.getText();
       bdb.put("Email", u);
       bdb.put("T3",t3);
       bdb.put("T4",t4);    
       bdb.put("TSH",tsh);
       dbc2.insert(bdb);
       BasicDBObject search = new BasicDBObject();
       BasicDBObject newQ = new BasicDBObject();
       BasicDBObject newP=new BasicDBObject();
                       /*bdb1.put("Email",u);
                       bdb1.put("T3",t3);
                       bdb1.put("T4",t4);
                       bdb1.put("TSH",tsh);  
                      dbc2.insert(bdb1);*/
        if(txtT3.getText().trim().length() == 0 || jftT1.getText().trim().length() == 0 || jftT2.getText().trim().length() == 0 )
  {
      JOptionPane.showMessageDialog(null,"Enter all test values");
  }
        else
        {
                   
                      
       DBCursor cursor = dbc.find();
        while(cursor.hasNext())     
                {
                    DBObject obj = cursor.next();                    
                   user=(String)obj.get("Email");
                   if(u.equals(user))
                   {
                     fnm=(String)obj.get("Fname");  
                     lnm=(String)obj.get("Lname");  
                    
                   }   
                   }
                    
              DBCursor cursor2 = dbc1.find();
              while(cursor2.hasNext())     
              {
                  DBObject obj2 = cursor2.next();
                  
                  
                  //d = (String)obj2.get("Thyroid");
                  
                  user=(String)obj2.get("Email"); 
                  
                   
                   if(u.equals(user)){
                       //System.out.println("3");
                        //if(d.equals("1"))
                        if(obj2.containsField("Thyroid"))
                        {
                              // System.out.println("2");
                            BasicDBObject searchQuery = new BasicDBObject("Email",u);
                            BasicDBObject updateFields = new BasicDBObject();
                            updateFields.append("T3",t3);
                            updateFields.append("T4", t4);
                            updateFields.append("TSH", tsh);
                            //System.out.println("done");
                            BasicDBObject setQuery = new BasicDBObject();
                            setQuery.append("$set", updateFields);
                            dbc1.update(searchQuery, setQuery);
                            flag=1;
                            break;
                          }
                       else
                        {
                        //System.out.println("1");
                            //search.append("Email",u );
                            // newQ.append("$set", new BasicDBObject().append("", ""));
                            //dbc1.update(search, newQ);
                           search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("Thyroid", "Test"));
                       dbc1.update(search, newQ); 
                        search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("T3",t3));
                       dbc1.update(search, newQ);
                        search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("T4",t4));
                        dbc1.update(search, newQ);
                        search.append("Email",u );
                       newQ.put("$set", new BasicDBObject().append("TSH",tsh));
                        dbc1.update(search, newQ);
                            flag=1;
                            break;
                            
                        }
                   }
              }   
        } 
                   if(flag==0)    
                   {
                    
                      newQ.put("Fname",fnm);
                      newQ.put("Lname",lnm); 
                      newQ.put("Email",u);
                      newQ.put("Thyroid","1");
                      newQ.put("T3",t3);
                      newQ.put("T4",t4);
                      newQ.put("TSH",tsh);  
                      dbc1.insert(newQ); 
                     
                   }
                   
      float a = Float.parseFloat(txtT3.getText());
      float b = Float.parseFloat(jftT1.getText());
      float c = Float.parseFloat(jftT2.getText());
      if((c<1) ||(b>12 || a>200) )
      {
          if(b>12)
          thyroid.setText("T4 is high and TSH is low"+"\n"+"It is an indicator of Hyperthyroidism(over-active thyroid)");
          if(a>200)
           thyroid.setText("T3 is high and TSH is low"+"\n"+"It is an indicator of Hyperthyroidism(over-active thyroid)");   
      }
      else if((c>5) ||(a<60 || b<4))
      {
          if(b<4)
          thyroid.setText("T4 is low and TSH is high"+"\n"+"It is an indicator of Hypothyroidism(under-active thyroid)");
          if(a>200)
           thyroid.setText("T3 is low and TSH is high"+"\n"+"It is an indicator of Hypothyroidism(under-active thyroid)");   

      }
      
      else
      {
       thyroid.setText("Test results are Normal :)");
      }
          
          
    
          
         // final JPanel p2=new JPanel();
        //final JOptionPane jo=new JOptionPane();

    }//GEN-LAST:event_btnT1ActionPerformed

    private void txtT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtT3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtT3ActionPerformed

    private void txtT3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtT3KeyTyped
        char c=evt.getKeyChar();
      //if((!Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))
      if(Character.isLetter(c) && !evt.isAltDown() || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
          }
      
     else{
     lblT3Error.setText("");
     }
      
    }//GEN-LAST:event_txtT3KeyTyped

    private void jftT1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT1KeyTyped
         char d=evt.getKeyChar();
      //if((!Character.isDigit(d)) || (d==KeyEvent.VK_BACK_SPACE) || (d==KeyEvent.VK_DELETE))
        if(Character.isLetter(d) && !evt.isAltDown() || (d==KeyEvent.VK_BACK_SPACE) || (d==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
          } 
        
     else{
     lblT3Error.setText("");
     }
      
      
    }//GEN-LAST:event_jftT1KeyTyped

    private void jftT2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftT2KeyTyped
         char e=evt.getKeyChar();
   
     if(Character.isLetter(e) && !evt.isAltDown() || (e==KeyEvent.VK_BACK_SPACE) || (e==KeyEvent.VK_DELETE))
        {
             getToolkit().beep();
             lblT3Error.enable(true);
             lblT3Error.setText("Enter only numbers !!!");
             evt.consume();
         } 
     else{
     lblT3Error.setText("");
     }
    }//GEN-LAST:event_jftT2KeyTyped

    private void txtT3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtT3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtT3KeyPressed

    private void jftT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT1ActionPerformed

    private void btnT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnT2ActionPerformed
        // TODO add your handling code here:
        menuPage m=new menuPage(u);
        m.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnT2ActionPerformed

    private void jftT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftT2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(thyroidTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(thyroidTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(thyroidTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(thyroidTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new thyroidTest(u).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnT1;
    private javax.swing.JButton btnT2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JFormattedTextField jftT1;
    private javax.swing.JFormattedTextField jftT2;
    private javax.swing.JLabel lblT1;
    private javax.swing.JLabel lblT11;
    private javax.swing.JLabel lblT14;
    private javax.swing.JLabel lblT15;
    private javax.swing.JLabel lblT18;
    private javax.swing.JLabel lblT19;
    private javax.swing.JLabel lblT2;
    private javax.swing.JLabel lblT3;
    private javax.swing.JLabel lblT3Error;
    private javax.swing.JLabel lblT4;
    private javax.swing.JLabel lblT5;
    private javax.swing.JLabel lblT6;
    private javax.swing.JLabel lblT7;
    private javax.swing.JLabel lblT8;
    private javax.swing.JLabel lblT9;
    private javax.swing.JLabel lblresult;
    private javax.swing.JTextArea thyroid;
    private javax.swing.JFormattedTextField txtT3;
    // End of variables declaration//GEN-END:variables

    private static class thyroid {

        public thyroid() {
        }

        private void append(String hello_World) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private void setText(String hello_World) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
